version: '3.6'
services:
  bookie:
    build: .
    command: flask run --host=0.0.0.0
    volumes:
      - "./app:/usr/src/app"
    ports:
      - 5000:5000
    depends_on: 
      - db
    environment: 
      DB_HOST: db
      DB_USERNAME: postgres
      DB_PASSWORD: example

  db:
    image: postgres:13.2
    restart: always
    volumes:
      - ./db/postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
      - ./venv/db:/var/lib/postgresql/data
    environment: 
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    